services:
  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./src:/var/www/html"
      - "./logs:/var/www/logs/novel_archive"
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      LOG_PATH: ${LOG_PATH}

  mysql:
    image: mysql:8.1.0
    container_name: mysql_8.1.0_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - "./dump:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    
